export const homeObjOne = {
    id: "about",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Health",
    headline: "Suggest the best balanced diet.",
    description: "Optimize the nutritional balance for your body.",
    buttonLabel: "Get started",
    imgStart: false,
    img: require("../../images/svg-6.svg").default,
    alt: "Health",
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: "discover",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Health",
    headline: "Suggest the best balanced diet.",
    description: "Optimize the nutritional balance for your body.",
    buttonLabel: "Get started",
    imgStart: true,
    img: require("../../images/svg-2.svg").default,
    alt: "Fitness",
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: "signup",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Health",
    headline: "Suggest the best balanced diet.",
    description: "Optimize the nutritional balance for your body.",
    buttonLabel: "Start Now",
    imgStart: false,
    img: require("../../images/svg-1.svg").default,
    alt: "Analize",
    dark: false,
    primary: false,
    darkText: true,
};