export const homeObjOne = {
    id: "about",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Papuricaとは？",
    headline: "あなたの身体作りをサポートします",
    description: "Papuricaはあなたの目標とする身体を築くために必要なカロリー・栄養素を計算し、サポート致します。",
    buttonLabel: "必要な栄養素を計算する",
    imgStart: false,
    img: require("../../images/svg-6.svg").default,
    alt: "Health",
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: "discover",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "筋トレ",
    headline: "フィットネスに関する情報",
    description: "科学的な根拠に基づいた効果的な筋トレの情報を発信します。",
    buttonLabel: "見にいく",
    imgStart: true,
    img: require("../../images/svg-2.svg").default,
    alt: "Fitness",
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: "signup",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "会員になると",
    headline: "管理画面の使用が可能",
    description: "1日に摂取した栄養素の記録や、不足した栄養素のレコメンド機能など、便利な機能が使用可能になります。",
    buttonLabel: "新規登録",
    imgStart: false,
    img: require("../../images/svg-1.svg").default,
    alt: "Analize",
    dark: false,
    primary: false,
    darkText: true,
};